spring:
    profiles:
        active: local

---

spring:
    profiles: local

server:
    port:
        8080

---

spring:
    profiles: dev

server:
    port:
        8081
---

spring:
    profiles: prod

server:
    port:
        8082