
spring:
  main:
    allow-bean-definition-overriding: true # boot 2.1 이후 빈 중복생성 막혔기 때문에 선언.
  jpa: # jpa
    show-sql : true
    generate-ddl : false
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create # 자동생성 끄기 : none
    properties:
      hibernate:
        show_sql : true
        use_sql_comments : true
        format_sql : true
        jdbc.lob.non_contextual_creation: true
        temp.use_jdbc_metadata_defaults: false
  datasource1: # postgresql
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/domiworld
    username: postgres
    password: 1715
    hikari:
      auto-commit: false
      connection-test-query: SELECT 1
      minimum-idle: 10
      maximum-pool-size: 50
      transaction-isolation: TRANSACTION_READ_UNCOMMITTED
      pool-name: pool-domiworld
  datasource2: # h2
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
    initialization-mode: always
    schema: classpath:h2/schema.sql
    data: classpath:h2/data.sql
  h2:
    console:
      enabled: true
      path: /h2-console
  thymeleaf:
      prefix : classpath:templates/
      suffix : .html
      cache : false
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    jdbc-type-for-null: varchar

mybatis.type-aliases-package : com.domiworld
mybatis.mapper-locations : mybatis/mapper/**/*.xml   

logging:
  pattern:
    console: "%d %-5level %logger : %msg%n"
  level:
    org.springframework: info
    org.hibernate: debug

